# Generated by Django 2.1.7 on 2019-06-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("polls", "0003_question_question_img")]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_img",
            field=models.ImageField(null=True, upload_to="images/", verbose_name="Img"),
        )
    ]
