# Generated by Django 2.1.7 on 2019-06-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("polls", "0002_auto_20190612_2033")]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_img",
            field=models.ImageField(null=True, upload_to="images/"),
        )
    ]
